### ISSUE TITLE
SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED error in Python 11

### ISSUE THREAD

**Issue by sowdm** [openpolicedata/openpolicedata#138]
In Python 11, accessing data on certain sites appears to not be possible with a basic requests call:

```
>>> import requests
>>> # Same issue with https://opendata.baltimorecity.gov/egis/rest/services/Hosted/911_Calls_For_Service_2017_csv/FeatureServer/
>>> url = "https://xmaps.indy.gov/arcgis/rest/services/OpenData/OpenData_NonSpatial/MapServer/5/"                            
>>> r = requests.get(url)
Traceback (most recent call last):
  File "C:\Users\matth\.conda\envs\opd-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matth\.conda\envs\opd-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\matth\.conda\envs\opd-py3.11\Lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\matth\.conda\envs\opd-py3.11\Lib\site-packages\urllib3\connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\matth\.conda\envs\opd-py3.11\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matth\.conda\envs\opd-py3.11\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matth\.conda\envs\opd-py3.11\Lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matth\.conda\envs\opd-py3.11\Lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matth\.conda\envs\opd-py3.11\Lib\site-packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='xmaps.indy.gov', port=443): Max retries exceeded with url: /arcgis/rest/services/OpenData/OpenData_NonSpatial/MapServer/5/ (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:992)')))
```

If using conda: how to install Python 3.11 with conda (not available through the main channel yet): https://stackoverflow.com/questions/74959226/how-to-pick-python-3-11-as-a-conda-environment-in-vs-code

I have seen this solution suggested: https://stackoverflow.com/a/71646353/9922439. The question I have is does this make the request in a comparable way to Python 3.10 or is it something different and perhaps we should be concerned that there is a security concern. 

I have also seen the suggestion to downgrade the cryptography package: https://pyquestions.com/ssl-error-unsafe-legacy-renegotiation-disabled. Not sure if that is a workable solution if someone is using an environment where other installed packages use requests.

**Comment by sowdm** [comment]
Ended up implementing OP_LEGACY_SERVER_CONNECT option in stackoverflow answer. Decided this was secure enough because Python 3.10 connects to these sites and it's documented by openssl:

https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_options.html
SSL_OP_LEGACY_SERVER_CONNECT: Allow legacy insecure renegotiation between OpenSSL and unpatched servers only: this option is currently set by default. See the SECURE RENEGOTIATION section for more details.
